zh-Hant-TW: zh-TW
zh-Hant-HK: zh-CN
es-US: es
it-IT: it
id-ID: id
fr-CA: fr
en-IN: en
en-GB: en
es-MX: es
da-DK: da
ru-RU: ru
th-TH: th
sv-SE: sv
fr-FR: fr
es-ES: es
en-US: en
en-SG: en
en-CA: en
en-AU: en
de-DE: de
zh-Hans-CN: zh-Hans
pt-BR: pt-BR
ko-KR: ko
en-AA: en
vi-VN: vi
es-AR: es
en-NZ: en
en-MY: en
ja-JP: ja
en-PH: en
el-GR: el
fi-FI: fi
nl-NL: nl
ro-RO: ro